# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import basic_paxos_pb2 as basic__paxos__pb2


class BasicPaxosStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.acceptor_prepare = channel.unary_unary(
        '/basicpaxos.BasicPaxos/acceptor_prepare',
        request_serializer=basic__paxos__pb2.AcceptorPrepareRequest.SerializeToString,
        response_deserializer=basic__paxos__pb2.AcceptorPrepareResponse.FromString,
        )
    self.acceptor_accept = channel.unary_unary(
        '/basicpaxos.BasicPaxos/acceptor_accept',
        request_serializer=basic__paxos__pb2.AcceptorAcceptRequest.SerializeToString,
        response_deserializer=basic__paxos__pb2.AcceptorAcceptResponse.FromString,
        )


class BasicPaxosServicer(object):
  """The greeting service definition.
  """

  def acceptor_prepare(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def acceptor_accept(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BasicPaxosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'acceptor_prepare': grpc.unary_unary_rpc_method_handler(
          servicer.acceptor_prepare,
          request_deserializer=basic__paxos__pb2.AcceptorPrepareRequest.FromString,
          response_serializer=basic__paxos__pb2.AcceptorPrepareResponse.SerializeToString,
      ),
      'acceptor_accept': grpc.unary_unary_rpc_method_handler(
          servicer.acceptor_accept,
          request_deserializer=basic__paxos__pb2.AcceptorAcceptRequest.FromString,
          response_serializer=basic__paxos__pb2.AcceptorAcceptResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'basicpaxos.BasicPaxos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
